fields:
- mode: NULLABLE
  name: date
  type: DATE
- mode: NULLABLE
  name: country
  type: STRING
- mode: NULLABLE
  name: locale
  type: STRING
- mode: NULLABLE
  name: version
  type: STRING
- mode: NULLABLE
  name: visits
  type: INTEGER
- mode: NULLABLE
  name: bounces
  type: INTEGER
